flask:
  upload_folder: ./flask_app/static/upload
  secret_key: mysecretkey
  session_type: filesystem
  debug: 0
  api_host: 0.0.0.0
  api_port: 5000

tensorflow:
  cuda_visible_devices: "-1"
  model_path: ./model/animals_EfficientNetB0.h5